お知らせ一覧ページの追加
actlaboratory/site pull request #65
Opened 2021-06-07 06:29 UTC by hrk-fujii

- 年ごとの、お知らせ一覧を表示するページの追加
- トップページにお知らせ一覧ページへのボタンの追加と、表示件数削減

2021-06-07 14:24 UTC, yamahubuki reviewed
- デフォルトで現在年が表示される仕様となっていますが、「最新のお知らせがある年」としてください。でないと、空白ページが出てしまいます。
- Daoはもっとシンプルに書けます。 そもそも、年別のお知らせ一覧表示は #51 でやってあるので参考にするなり持ってくるなりしてください。

2021-06-07 14:25 UTC, yamahubuki requested changes
- デフォルトで現在年が表示される仕様となっていますが、「最新のお知らせがある年」としてください。でないと、空白ページが出てしまいます。
- Daoはもっとシンプルに書けます。 そもそも、年別のお知らせ一覧表示は #51 でやってあるので参考にするなり持ってくるなりしてください。

2021-06-08 05:43 UTC, hrk-fujii commented
- デフォルト年と、DAOコードを修正しました。
- 年別取得は、年一覧取得とともにSQLのdate型にのっかって書いています。
    -  #51 の記述に意図がある場合は、セットで修正しないとコードが読みづらくなると思います。

2021-06-08 13:43 UTC, yamahubuki requested changes
昨日見落としてて申し訳ないが、将来性のため、修正お願いします。

2021-06-08 13:43 UTC, yamahubuki commented on app/Model/Dao/Informations.php
> +            ->select('DISTINCT YEAR(date) as date')
yearをdateという名前で取得するのはひどすぎます。将来、確実に間違えます。
せめて、as yearにしてください。

2021-06-08 13:43 UTC, yamahubuki commented on app/Model/Dao/Informations.php
> +        return $result;
そもそも、1要素しか取らないのであれば、この関数内で結果を加工してint型配列で返す方が使いやすいと思います。

2021-06-08 16:02 UTC, yamahubuki approved these changes

2021-06-08 16:03 UTC, merged