twitterイベントのslack通知
actlaboratory/site pull request #71
Opened 2021-09-28 12:32 UTC by guredora403

twitter account activity APIのウェブフックを利用して、環境変数に設定されているツイッターアカウントでのイベントがslackに通知されるようになります。
初めに
/api/registerTwitterWebhook?password=script_password
を実行してtwitterにウェブフックのURLを登録する必要があります。
また、twitterの通知を区別できるように専用のslack URLを設けてあります。

2021-09-28 13:34 UTC, yncat reviewed
コメントしました

2021-09-28 13:34 UTC, yncat commented on app/Controller/api/registerTwitterWebhook.php
> +    //$url = str_replace("http://", "https://", $url);
このコメントアウト消えてないのは意図通りですか？

2021-09-28 13:34 UTC, yncat commented on app/Controller/api/registerTwitterWebhook.php
> +        $logger->info("twitter regist error");
「登録する」を「regist」だと思ってる開発者は多いようなんですが、「register」が正しいです。

2021-09-28 13:34 UTC, yncat commented on app/Controller/api/twitterWebhook.php
> +    //$logger->debug(var_export($my_user, true));
このコメントアウトは消さなくていいですか？

2021-09-28 13:34 UTC, yncat commented on app/Util/SlackUtil.php
> +	static function twitter_message($body){
twitter_messageとtwitter_notifyはなにが違うんですか？

2021-09-28 14:17 UTC, yamahubuki requested changes
slackUtilの関数は口頭で話した内容に沿って整理しておいてください。
twitterMessage()とかは削除で。

2021-09-28 14:17 UTC, yamahubuki commented on app/Controller/api/registerTwitterWebhook.php
> +use Util\EnvironmentUtil;
これ使ってなさげ

2021-09-28 15:11 UTC, yamahubuki submitted a review, later dismissed

2021-09-28 15:12 UTC, guredora403 commented on app/Controller/api/registerTwitterWebhook.php
> +    //$url = str_replace("http://", "https://", $url);
はい。テスト用に必要でした。

2021-09-28 15:19 UTC, guredora403 commented on app/Util/SlackUtil.php
> +	static function twitter_message($body){
notifyはいいねやツイートなどの通知で、messageはDM用です。現愛はtwitter_messageは削除されています。

2021-09-29 12:00 UTC, yncat approved these changes
LGTM!

2021-09-29 12:06 UTC, merged